apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-exp-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$AWS_ACCOUNT_ID:role/oidc_exp_federated_role
